name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:  # Run tests on the oldest and newest supported version of Python.
        python-version: [3.8, 3.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.8.4

      - name: Set up Poetry environment
        run: |
          poetry cache clear PyPI --all
          poetry install --no-root

      - name: Run ruff
        run: |
          poetry run ruff check .

      - name: Run ruff format
        run: |
          poetry run ruff format --check .

      - name: Run mypy
        run: |
          poetry run mypy --show-error-codes .

      - name: Run tests
        run: |
          export QSTASH_TOKEN="${{ secrets.QSTASH_TOKEN }}"
          export QSTASH_CURRENT_SIGNING_KEY="${{ secrets.QSTASH_CURRENT_SIGNING_KEY }}"
          export QSTASH_NEXT_SIGNING_KEY="${{ secrets.QSTASH_NEXT_SIGNING_KEY }}"
          export OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
          poetry run pytest
